insert into userdata(username, password, email, telephone, student) values ('Estevam', 'senhateste','estevam@estevam', '3258', TRUE);
insert into userdata(username, password, email, telephone, student) values ('user', '1234','user@gmail.com', '1234-1234', TRUE);
insert into category(name) values('Aula de Matematica');
insert into category(name) values('Aula de Ingles');
-- insert into offer(name, userid, categoryid) values ('Aula basica', 1, 2);
insert into request (name, description, extrainfo, minprice, maxprice,  userid, categoryid, timestamp ) values ('Aula', 'Calculo I', '', 20, 40, 1, 1, current_timestamp);
insert into request (name, description, extrainfo, minprice, maxprice,  userid, categoryid, timestamp ) values ('Aula', 'Calculo II', '', 20, 40, 1, 1, current_timestamp);
insert into request (name, description, extrainfo, minprice, maxprice,  userid, categoryid, timestamp ) values ('Aula', 'Calculo III', '', 20, 40, 1, 1, current_timestamp);
insert into request (name, description, extrainfo, minprice, maxprice,  userid, categoryid, timestamp ) values ('Aula', 'Calculo IV', '', 20, 40, 1, 1, current_timestamp);
insert into request (name, description, extrainfo, minprice, maxprice,  userid, categoryid, timestamp ) values ('Aula', 'Phrasal Verbs', '', 20, 40, 1, 2, current_timestamp);
insert into request (name, description, extrainfo, minprice, maxprice,  userid, categoryid, timestamp ) values ('Aula', 'Present Perfect', '', 20, 40, 1, 2, current_timestamp);
